/*
    Author  : Yipeng Liu
    Project : Assignment 4
    Class   : Student
    Date    : 07/20/2021
 */
package edu.sjsu.assignment4;

import java.util.Objects;

/**
 * A student with ID and name.
 *
 * @author Yipeng Liu
 */
public class Student implements Comparable<Student> {
    private int id;
    private String name;

    public Student(int id, String name) {
        this.id = id;
        this.name = name;
    }

    public Student(int id) {
        this.id = id;
        this.name = "Unnamed";
    }

    public int getId() {
        return this.id;
    }

    public String getName() {
        return this.name;
    }

    /**
     * A student with the same ID is considered as the same student.
     * If ID is different, but name is the same, it is considered as
     * a different student.
     *
     * @param o
     *      A different {@code Student}.
     *
     * @return
     *      < 0 if this id is less than the other id;
     *      = 0 if same id;
     *      > 0 if this id is greater than the other id.
     */
    @Override
    public int compareTo(Student o) {
        return this.id - o.id;
    }

    /**
     * An Overridden method for the equals function which only checks
     * the student ID. Autogenerated using IntelliJ.
     *
     * @param o
     *      {@code Object}
     *
     * @return
     *      boolean
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Student student = (Student) o;
        return id == student.id;
    }

    /**
     * Autogenerated using Intellij.
     *
     * @return
     */
    @Override
    public int hashCode() {
        return Objects.hash(id);
    }

    /**
     * Only returns the {@code Student} name.
     *
     * @return
     *      A name {@code String}.
     */
    @Override
    public String toString() {
        return this.id + "." + this.name;
    }
}
